workflows:
  workflow:
    jobs:
      - build:
          name: build-v<< matrix.version >>
          matrix:
            parameters:
              version: [ "0.1", "0.2" ]
      - deploy:
          name: deploy-v<< matrix.version >>
          matrix:
            parameters:
              version: [ "0.1", "0.2" ]
          requires:
            - build-v<< matrix.version >>
  daily:
    jobs:
      - build:
          name: build-v<< matrix.version >>
          matrix:
            parameters:
              version:
                - "0.1"
                - "0.2"
    triggers:
      - schedule:
          cron: 0 4 * * *
          filters:
            branches:
              only:
                - main
